"""rename_difficulty_to_frequency

Revision ID: 30a2d39d977e
Revises: ee7adc9d5074
Create Date: 2026-07-14 15:51:07.785814
"""
from alembic import op
import sqlalchemy as sa



revision = '30a2d39d977e'
down_revision = 'ee7adc9d5074'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview_questions', 'difficulty', new_column_name='frequency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview_questions', 'frequency', new_column_name='difficulty')
    # ### end Alembic commands ###
