"""remove discussion_thread_id

Revision ID: 405f61ad397d
Revises: 20260720_0031
Create Date: 2026-07-21 06:44:41.524373
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '405f61ad397d'
down_revision = '20260720_0031'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Drop constraints and columns first
    op.drop_constraint(op.f('fk_interview_questions_discussion_thread'), 'interview_questions', type_='foreignkey')
    op.drop_index(op.f('ix_interview_questions_discussion_thread_id'), table_name='interview_questions')
    op.drop_column('interview_questions', 'discussion_thread_id')

    op.drop_constraint(op.f('fk_question_comments_discussion_thread'), 'question_comments', type_='foreignkey')
    op.drop_index(op.f('ix_question_comments_discussion_thread_id'), table_name='question_comments')
    op.drop_column('question_comments', 'discussion_thread_id')

    # Now drop the table and its index
    op.drop_index(op.f('ix_question_discussion_threads_canonical_question_id'), table_name='question_discussion_threads')
    op.drop_table('question_discussion_threads')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_comments', sa.Column('discussion_thread_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_question_comments_discussion_thread'), 'question_comments', 'question_discussion_threads', ['discussion_thread_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_question_comments_discussion_thread_id'), 'question_comments', ['discussion_thread_id'], unique=False)
    op.add_column('interview_questions', sa.Column('discussion_thread_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_interview_questions_discussion_thread'), 'interview_questions', 'question_discussion_threads', ['discussion_thread_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_interview_questions_discussion_thread_id'), 'interview_questions', ['discussion_thread_id'], unique=False)
    op.create_table('question_discussion_threads',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('canonical_question_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['canonical_question_id'], ['interview_questions.id'], name=op.f('question_discussion_threads_canonical_question_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('question_discussion_threads_pkey')),
    sa.UniqueConstraint('canonical_question_id', name=op.f('question_discussion_threads_canonical_question_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_question_discussion_threads_canonical_question_id'), 'question_discussion_threads', ['canonical_question_id'], unique=False)
    # ### end Alembic commands ###
