"""user_questions_progress_overrides

Revision ID: e27911281310
Revises: 20260718_0019
Create Date: 2026-07-19 04:46:01.427036
"""
from alembic import op
import sqlalchemy as sa



revision = 'e27911281310'
down_revision = '20260718_0019'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_question_tag_association',
    sa.Column('user_question_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['interview_tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_question_id'], ['user_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_question_id', 'tag_id')
    )
    op.drop_constraint(op.f('interview_collections_slug_key'), 'interview_collections', type_='unique')
    op.create_index(op.f('ix_interview_collections_slug'), 'interview_collections', ['slug'], unique=True)
    op.add_column('user_questions', sa.Column('category_id', sa.UUID(), nullable=True))
    op.add_column('user_questions', sa.Column('frequency', sa.String(length=50), nullable=True))
    op.add_column('user_questions', sa.Column('importance_score', sa.Integer(), nullable=True))
    op.add_column('user_questions', sa.Column('my_answer', sa.Text(), nullable=True))
    op.add_column('user_questions', sa.Column('improvement_notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_user_questions_category_id'), 'user_questions', ['category_id'], unique=False)
    op.create_foreign_key(None, 'user_questions', 'interview_categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # --- Data Migration ---
    connection = op.get_bind()
    
    # 1. Copy progress fields from interview_questions to user_questions
    connection.execute(sa.text("""
        UPDATE user_questions uq
        SET category_id = iq.category_id,
            frequency = iq.frequency,
            importance_score = iq.importance_score,
            my_answer = iq.my_answer,
            improvement_notes = iq.improvement_notes
        FROM interview_questions iq
        WHERE uq.question_id = iq.id
    """))

    # 2. Copy tag associations to user_question_tag_association
    connection.execute(sa.text("""
        INSERT INTO user_question_tag_association (user_question_id, tag_id)
        SELECT uq.id, qta.tag_id
        FROM question_tag_association qta
        JOIN interview_tags t ON qta.tag_id = t.id
        JOIN user_questions uq ON qta.question_id = uq.question_id AND t.user_id = uq.user_id
        ON CONFLICT DO NOTHING
    """))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_questions', type_='foreignkey')
    op.drop_index(op.f('ix_user_questions_category_id'), table_name='user_questions')
    op.drop_column('user_questions', 'improvement_notes')
    op.drop_column('user_questions', 'my_answer')
    op.drop_column('user_questions', 'importance_score')
    op.drop_column('user_questions', 'frequency')
    op.drop_column('user_questions', 'category_id')
    op.drop_index(op.f('ix_interview_collections_slug'), table_name='interview_collections')
    op.create_unique_constraint(op.f('interview_collections_slug_key'), 'interview_collections', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_table('user_question_tag_association')
    # ### end Alembic commands ###
